# Generated by Django 4.0.6 on 2022-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('event_price', models.IntegerField()),
            ],
        ),
    ]
