# Generated by Django 4.0.6 on 2022-08-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='New_Event',
        ),
    ]
