# Generated by Django 4.0.6 on 2022-08-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0002_rename_event_new_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Event',
            new_name='Event_table',
        ),
    ]
