# Generated by Django 4.0.6 on 2022-08-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0006_event_table_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event_price',
        ),
    ]
